---
version: "3.2"

services:
  evidently:
    build: ../.
    env_file:
      - evidently_env
    volumes:
      # Add the location of remittance files and other Oscar documents.
      # We are using a `bind` here only because we found it non-trivial to use
      # a `read_only` volume that uses an absolute path as its source.
      - type: bind
        source: /root/open-osp/volumes/OscarDocuments
        target: /data
        read_only: true
      # Add the public key that we use to encrypt the file.
      - ./evidently_rsa.pub.pem:/app/encrypt.pub.pem
      # Add the RSA key for the end user SFTP access.
      - ./sftp_rsa:/app/sftp.pk
